const listaDeAbrigos = [
    {
        id: 1,
        nome: "Abrigo Luz do Amanhã",
        enderecoCompleto: "Rua da Esperança, 123, Bairro Solidariedade, São Paulo - SP",
        enderecoResumido: "Rua da Esperança, 123",
        distanciaSimulada: "1.5km",
        tipo: "Oficial",
        vagasDisponiveis: 10,
        vagasTotais: 50,
        latitude: -23.550520,
        longitude: -46.633308,
        horarioFuncionamento: "Aberto 24 horas",
        servicos: ["Alimentação", "Pernoite", "Banho", "Apoio Psicológico"],
        contatoTelefone: "(11) 99999-8888",
        contatoEmail: "contato@luzdoamanha.org"
    },
    {
        id: 2,
        nome: "Casa de Apoio Fraterno",
        enderecoCompleto: "Avenida Acolhedora, 789, Centro, São Paulo - SP",
        enderecoResumido: "Avenida Acolhedora, 789",
        distanciaSimulada: "3km",
        tipo: "Improvisado",
        vagasDisponiveis: 5,
        vagasTotais: 10,
        latitude: -23.560520,
        longitude: -46.643308,
        horarioFuncionamento: "Das 18h às 08h",
        servicos: ["Pernoite", "Jantar"],
        contatoTelefone: "(11) 98888-7777",
        contatoEmail: "apoiofraterno@email.com"
    },
    {
        id: 3,
        nome: "Centro de Acolhida Esperança",
        enderecoCompleto: "Rua da Paz, 456, Vila Nova, São Paulo - SP",
        enderecoResumido: "Rua da Paz, 456",
        distanciaSimulada: "2.2km",
        tipo: "Oficial",
        vagasDisponiveis: 15,
        vagasTotais: 30,
        latitude: -23.545520,
        longitude: -46.623308,
        horarioFuncionamento: "Das 20h às 07h",
        servicos: ["Alimentação", "Pernoite", "Banho", "Atendimento Médico Básico"],
        contatoTelefone: "(11) 97777-6666",
        contatoEmail: "esperanca@acolhida.org"
    },
    {
        id: 4,
        nome: "Abrigo São Francisco",
        enderecoCompleto: "Rua da Caridade, 789, Bairro São Francisco, São Paulo - SP",
        enderecoResumido: "Rua da Caridade, 789",
        distanciaSimulada: "4km",
        tipo: "Oficial",
        vagasDisponiveis: 8,
        vagasTotais: 25,
        latitude: -23.565520,
        longitude: -46.653308,
        horarioFuncionamento: "Aberto 24 horas",
        servicos: ["Alimentação", "Pernoite", "Banho", "Apoio Psicológico", "Atendimento Médico Básico"],
        contatoTelefone: "(11) 96666-5555",
        contatoEmail: "saofrancisco@abrigo.org"
    }
]; 